name: Build Tarball

on:
  workflow_call: {}

jobs:
  tar:
    name: Tarball 🛠️ (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            config: default
            filename: nixos.wsl
            runner: ubuntu-24.04
          - arch: aarch64
            config: default_aarch64
            filename: nixos-arm64.wsl
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Set Version 🏷️
        uses: ./.github/actions/version
        id: version

      - name: Summary Headline 📝
        run: echo '## NixOS-WSL ${{ steps.version.outputs.version }} (${{ matrix.arch }})' >> $GITHUB_STEP_SUMMARY

      - name: Build Tarball 🛠️
        uses: ./.github/actions/build-wsl-tarball
        with:
          config: ${{ matrix.config }}
          filename: ${{ matrix.filename }}

      - name: Upload Tarball 📤
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: tarball-${{ matrix.arch }}
          path: ${{ matrix.filename }}
