name: Checks

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  checks:
    name: Flake Check ❄️ (x86_64)
    strategy:
      fail-fast: false
      matrix:
        # Keep in sync with flake.nix outputs.checks.
        check: &checks_list
          - nixpkgs-fmt
          - nixpkgs-input
          - options-doc
          - rustfmt
          - side-effects
          - username
          - test-native-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Run Check 📋
        run: |
          nix build -L --impure --expr "with builtins; (getFlake (toString ./.)).checks.\${currentSystem}.${{ matrix.check }}"

  checks-aarch64:
    name: Flake Check ❄️ (aarch64)
    strategy:
      fail-fast: false
      matrix:
        check: *checks_list
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Run Check 📋
        run: |
          nix build -L --impure --expr "with builtins; (getFlake (toString ./.)).checks.\${currentSystem}.${{ matrix.check }}"
